[package]
name = "rolley_token"
version = "0.1.0"
authors = ["Emma / Banter"]

[addresses]
rolley_token = "_"
aptos_framework = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
